In [1]:
import torch

In [2]:
ft = torch.FloatTensor([[1,2], [3,4]])

ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
lt = torch.LongTensor([[1, 2], [3, 4]])

lt

tensor([[1, 2],
        [3, 4]])

In [4]:
bt = torch.ByteTensor(3, 2)

bt

tensor([[  0, 255],
        [  0,   0],
        [  0,   0]], dtype=torch.uint8)

In [5]:
# 임의의 값으로 채워진 원하는 크기의 텐서를 만들고자 한다면, 다음과 같이 간단하게 만들 수 있다.
x = torch.FloatTensor(3, 2)

x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
# 넘파이 호환
import numpy as np
x = np.array([[1, 2], [3, 4]]) # Define numpy array

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [7]:
# ndarray(numpy 배열)을 파이토치 텐서로 변환한다.
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [8]:
# 파이토치 텐서를 넘파이 ndarray로 변환한다.
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [9]:
# 텐서 타입 변환
# Float 타입 텐서를 Long 타입 텐서로 변환
print(ft.long()) # Float -> Long

print(lt.float()) # Long -> Float

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]])


In [10]:
# 텐서 크기 구하기
# 텐서 크기를 구하려면, size() 함수나 shape 속성에 접근한다.
# 두 방법의 차이는 없고, size() 함수의 결괏값이 shape 속성에 담겨있다고 보면 된다.
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

print(x.size())
print(x.shape)
# 크기 정보는 배열에담겨있다고 생각할 수 있다.
# 즉, 특정 차원의 크기를 알기 위해선, shape 속성의 해당 차원 인덱스에 접근하거나, size() 함수의 인자에 원하는 차원의 인덱스를 넣어주면 된다.
print(x.size(1), x.shape[1])

# 음수를 넣어주면 뒤에서부터의 순서에 해당한다.
print(x.size(-1), x.shape[-1])

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
2 2
2 2


In [11]:
# 텐서 차원의 개수 구하기
# 텐서 차원의 개수를 알기 위해선, dim() 함수를 활용한다.
# 이것은 shape 속성의 배열 크기와 같다.
print(x.dim())
print(len(x.size()))

3
3


In [12]:
# 요소별 산술 연산
a = torch.FloatTensor([[1, 2], [3, 4]])
b = torch.FloatTensor([[2, 2], [3, 3]])

# 행렬 사이의 덧셈
print(a + b)
# 행렬 사이의 뺄셈
print(a - b)
# 행렬 사이의 곱셈
print(a * b)
# 행렬 사이의 나눗셈
print(a / b)
# 행렬 제곱
print(a ** b)
# 논리 연산
print(a == b)
print(a != b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[ 1.,  4.],
        [27., 64.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])


In [13]:
# 인플레이스 연산
# 텐서 연산들의 결과 텐서는 메모리에 새롭게 할당된다.
# 즉, 빈 메모리의 공간에 결과 텐서가 할당되고 결과 텐서의 값이 위치하게 된다.

# 인플레이스(in-place) 연산은 같은 산술 연산을 수행하지만, 기존 텐서에 결과가 저장된다.
print(a)
print(a.mul(b)) # a.mul(b)의 연산 결과는 새로운 메모리에 할당된다. 즉, 텐서 a를 출력하면, a의 값은 그대로인 것을 볼 수 있다.
print(a)

# 인플레이스 연산들은 밑줄이 함수명 뒤에 붙어있는 것이 특징이다.
# 즉, 곱셈 함수의 인플레이스 연산은 mul_()으로 대응된다.
print("인플레이스 연산")
print(a.mul_(b))
# 즉, 연산 결과는 위와 같지만, 이 곱셈 연산의 결과는 텐서 a에 저장된다.
print(a)
# 파이토치는 가비지 컬렉터가 효율적으로 동작하기에 굳이 인플레이스 연산을 사용할 필요가 없다.

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
인플레이스 연산
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


In [14]:
# 차원 축소 연산 : 합과 평균
x = torch.FloatTensor([[1, 2], [3, 4]])
# sum(), mean() 함수를 통해, 행렬 전체 요소의 합과 평균을 구할 수 있다.
# 행렬 요소 전체의 합이나 평균은 텐서나 행렬이 아닌 스칼라 값으로 저장되므로, 차원이 축소된다고 볼 수 있다.
print(x.sum())
print(x.mean())

# 함수의 dim 인자에 원하는 연산의 차원을 넣어줄 수 있다.
# dim 인자의 값은 없어지는 차원이라고 생각할 수 있다.
print(x.sum(dim=0))
# dim=0이면, 첫 번째 차원을 이야기함으로 행렬의 세로축에 대해서 합 연산을 수행한다.
# 수식에서 T표시는 행렬의 행과 열을 바꿔 표현하는 전치(transpose) 연산을 의미한다.
# dim 인자에 -1을 넣어주면, 뒤에서 첫 번째 차원을 의미한다.
# 위에서는 2개의 차원만 존재하므로 dim=-1은 dim=1과 동일한 결과를 반환한다.
print(x.sum(dim=-1))

tensor(10.)
tensor(2.5000)
tensor([4., 6.])
tensor([3., 7.])


In [17]:
# 브로드캐스트 연산
# 크기가 다른 두 텐서를 갖고 산술 연산을 수행한다.

# 텐서 + 스칼라
# 행렬(텐서)에 스칼라를 더한다.
print("텐서 + 스칼라")
x = torch.FloatTensor([[1, 2], [3, 4]])
y = 1
z = x + y
print(z)
print(z.size())
# 행렬 x의 각 요소에 모두 1이 더해진다.

# 텐서 + 벡터
# 행렬에 벡터가 더해지는 경우
print("텐서 + 벡터")
x = torch.FloatTensor([[1, 2,], [4, 8]])
y = torch.FloatTensor([3, 5])
print(x.size()) # torch.Size([2, 2])
print(y.size()) # torch.Size([2])
# 크기가 다른 두 텐서 사이의 연산을 위해 브로드케스팅(broadcasting)이 적용된다.
# 차원에 맞춰 줄을 세우고 빈칸의 값이 1이라고 가정할 때 다른 한쪽에 똑같이 맞춘다.
# [2, 2]    [2, 2]    [2, 2]
# [   2] -> [1, 2] -> [2, 2]
z = x + y
print(z)

# 텐서들의 덧셈
print("텐서 들의 덧셈")
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3, 5])
print(x.size()) # torch.Size([1, 1, 2])
print(y.size()) # torch.Size([2])
# [1, 1, 2]    [1, 1, 2]
# [      2] -> [1, 1, 2]
z = x + y
print(z)
print(z.size())

# 텐서 + 텐서
# 이 브로드캐스팅규칙은 차원의 크기가 1인 차원에 대해서도 비슷하게 적용된다.
# 다음과 같인 두 텐서를 선언하고, 크기를 출력한다.
print("텐서 + 텐서")
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3], [5]])
print(x.size()) 
print(y.size())
# [1, 2] -> [2, 2]
# [2, 1] -> [2, 2]
z = x + y
print(z)
print(z.size())

텐서 + 스칼라
tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])
텐서 + 벡터
torch.Size([2, 2])
torch.Size([2])
tensor([[ 4.,  7.],
        [ 7., 13.]])
텐서 들의 덧셈
torch.Size([1, 1, 2])
torch.Size([2])
tensor([[[4., 7.]]])
torch.Size([1, 1, 2])
텐서 + 텐서
torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


In [26]:
# 텐서 형태 변환
# 텐서의 전체 요소(element) 개수는 유지한 채 모양을 바꾸는 방법

# 1. view 함수
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(x.size()) # torch.Size([3, 2, 2])
# view 함수의 인자로는 원하는 텐서의 크기를 넣어주면 된다.
# 중요한 점은 텐서의 요소 개수는 유지되어야 한다.
print(x.view(12)) # tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
print(x.view(3, 4))
'''
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
'''
print(x.view(3, 1, 4))
'''
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
'''

# 새로운 크기가 기존 텐서의 요소 개수와 맞지 않으면 오류가 발생하게 된다.
# 하지만, view 함수에 인자를 넣어줄 때 -1을 활용하여 일일이 요소 개수를 맞추기 위해 노력할 필요가 없다.
# -1을 활용하면, 일일이 요소 개수를 맞추기 위해 노력할 필요가 없다.
# -1이 들어간 차원의 크기는 다른 차원의 값들을 곱하고 남은 필요한 값이 자동으로 채워지게 된다.
print(x.view(-1)) # tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
print(x.view(3, -1))
'''
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
'''
print(x.view(-1, 1, 4))
'''
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
'''
# 이때 view 함수의 결과 텐서 주소는 바뀌지 않는다.
# 따라서 다음 코드에서 y의 값이 바뀌게 된다면, x의 값도 바뀌게 된다.
y = x.view(3, 4)
print(x.storage().data_ptr() == y.storage().data_ptr())

# view 함수는 메모리에 순차대로 선언된 텐서에 대해서만 작동한다.
# 위의 조건에 만족하지 않는다면 오류를 발생시키게 된다.
# 위의 오류가 발생한 상황에서 텐서 형태 변환을 진행하려면, contiguous 함수를 호출한 후, view 함수를 호출하면 된다.
# contiguous 함수는 텐서를 새로운 메모리상의 인접한 주소에 인접한 값을 순서대로 할당해주는 함수이다.
# 이미 메모리상에 원하는 형태로 존재한다면, 새롭게 할당하지 않고 해당 텐서를 contiguous 함수의 결괏값으로 그대로 반환한다.

# 2. reshape 함수를 활용할 수 도 있다.
# reshape 함수는 view 함수와 동일하게 작동하지만, contiguous 함수와 view 함수를 순차적으로 호출한 것과 동일하다.
print(x.reshape(3, 4))

torch.Size([3, 2, 2])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
True
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [29]:
# 3. squeeze 함수
x = torch.FloatTensor([[[1, 2], [3, 4]]])
print(x.size()) # torch.Size([1, 2, 2])
# squeeze 함수는 차원의 크기가 1인 차원을 없애주는 역할을 한다.
print(x.squeeze()) # tensor([[1., 2.],[3., 4.]])
print(x.squeeze().size()) # torch.Size([2, 2])
# 텐서 x의 첫 번째 차원의 크기가 1이었기 때문에 squeeze 함수를 통해 텐서 x의 형태는 2 x 2로 바뀌었다.
# 다른 함수들과 마찬가지로 squeeze의 경우에도 원하는 차원의 인덱스를 지정할 수 있다.
# 만약 해당 차원의 크기가 1이 아닌 경우 같은 텐서가 반환횐다.
print(x.squeeze(0).size()) # torch.Size([2, 2])
print(x.squeeze(1).size()) # torch.Size([1, 2, 2])

torch.Size([1, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([1, 2, 2])


In [32]:
# 4. unsqueeze 함수
# squeeze 함수의 반대 역할을 한다.
# unsqueeze 함수는 지정된 차원의 인덱스에 차원의 크기가 1인 차원을 삽입한다.
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.size()) # torch.Size([2, 2])

# 2 x 2 행렬에 unsqueeze를 수행하여 형태를 변환한다.
# 다른 함수들과 마찬가지로 차원의 인덱스에 음수를 넣어 뒤에서부터 접근할 수 있다.
print(x.unsqueeze(1).size())  # torch.Size([2, 1, 2])
print(x.unsqueeze(-1).size()) # torch.Size([2, 2, 1])
print(x.unsqueeze(2).size())  # torch.Size([2, 2, 1])

# reshape 함수를 이용하여 똑같이 구현할 수 있다.
print(x.reshape(2, 2, -1).size()) # torch.Size([2, 2, 1])

torch.Size([2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


In [43]:
# 텐서 자르기, 붙이기
# 하나의 텐서를 둘 이상으로 자르거나, 둘 이상의 텐서를 하나로 합친다.
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(x.size()) # torch.Size([3, 2, 2])

# x 텐서의 첫 번째 차원의 0번 인덱스만 잘라내고(슬라이싱) 싶다면 아래와 같이 구현한다.
print(x[0]) # tensor([[1., 2.],[3., 4.]])
# 첫 번째 차원(0번 인덱스)은 잘라내는 과정에서 사라진다.
# 즉, 3 x 2 x 2 크기의 텐서를 잘라내어, 2 x 2 크기의 행렬을 얻는다.

# 음수를 넣어서 뒤에서부터 접근하는 것도 가능하다.
print(x[-1]) # tensor([[ 9., 10.],[11., 12.]])

# 첫 번째 차원이 아닌 중간 차원에 대해서 비슷한 작업을 수행하고 싶을 경우에는 콜론(:) 기호를 사용하면 된다.
# 콜론을 사용하면, 해당 차원에서는 모든 값을 가져오라는 의미가 된다.
print(x[:, 0])
'''
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
'''

# 첫 번째 차원에서 인덱스 1 이상부터 2 이전까지의 부분을, 두 번째 차원에서는 1 이상부터의 부분을 마지막 차원에서는 전부를 가져왔을 때의 크기를 반환하는 코드이다.
print(x[1:2, 1:, :].size()) # torch.Size([1, 1, 2])

# 범위를 통해 텐서의 부분을 얻어낼 경우, 차원의 개수가 줄어들지 않는다.

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
torch.Size([1, 1, 2])


In [44]:
# 2. split 함수
# split 함수는 텐서를 특정 차원에 대하여 원하는 크기로 잘라준다.
# split 함수를 통해 첫 번째 차원의 크기가 4가 되도록 텐서를 등분한 후, 각각의 등분된 텐서 크기를 출력하는 코드이다.
x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)
for s in splits:
    print(s.size())
'''
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])
'''
# 주어진 텐서의 첫 번째 차원의 크기가 10이었기 때문에, 크기 4로 등분할 경우 마지막에 크기 2의 텐서가 남게 된다.
# 즉, 마지막 텐서의 크기는 다른 텐서들과 달리 2 x 4의 크기가 된 것을 볼 수 있다.

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [45]:
# 3. chunk 함수
# chunk 함수는 크기에 상관없이 원하는 개수로 나눈다.
x = torch.FloatTensor(8, 4)
# 첫 번째 차원의 크기 8을 최대한 같은 크기로 3등분한다.
chunks = x.chunk(3, dim=0)
for c in chunks:
    print(c.size())
'''
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])
'''

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


In [47]:
# 4. index select 함수
# 특정 차원에서 원하는 인덱스의 값만 취하는 함수이다.
# 다음 코드 같이 3 x 2 x 2 크기의 텐서를 만든다.
x = torch.FloatTensor([[[1, 1], [2, 2]], [[3, 3], [4, 4]], [[5, 5], [6, 6]]])
indice = torch.LongTensor([2, 1])
print(x.size()) # torch.Size([3, 2, 2])

# indice 텐서의 값을 활용하여, index_select 함수를 수행하면 다음과 같이 진행된다.
y = x.index_select(dim=0, index=indice)
print(y)
'''
tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
'''
print(y.size()) # torch.Size([2, 2, 2])

torch.Size([3, 2, 2])
tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [50]:
# 5. concatenate 함수
# 여러 텐서를 합쳐서 하나의 텐서로 만드는 방법이다.
# cat 함수의 이름은 Concatenate를 줄여서 부르는 이름이다.
# 배열(리스트) 내의 두 개 이상의 텐서를 순서대로 합쳐서 하나의 텐서로 반환한다.
# 합쳐지기 위해선, 다른 차원들의 크기가 같아야 한다.
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(x.size(), y.size()) # torch.Size([3, 3]) torch.Size([3, 3])

# 3 x 3 텐서 x, y가 있을 때 두 텐서를 원하는 차원으로 이어붙인다.
# 아래의 코드는 첫 번째 차원으로 이어붙이는 코드이다.
z = torch.cat([x, y], dim=0)
print(z)
'''
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
'''
print(z.size()) # torch.Size([6, 3])

# 마지막 차원(dim=-1)으로 텐서를 이어붙인다.
z = torch.cat([x, y], dim=-1)
print(z)
'''
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
'''
print(z.size()) # torch.Size([3, 6])

# 이어 붙이고자 하는 차원의 크기가 맞지 않으면 다음 그림과 같이 cat 함수를 수행할 수 없다.

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [53]:
# 6. stack 함수
# cat 함수와 비슷한 역할을 수행한다.
# stack 함수는 쌓기 작업을 수행한다.
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
z = torch.stack([x, y])
print(z)
'''
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
'''
print(z.size()) # torch.Size([2, 3, 3])
# 텐서 z의 크기를 출력하여 볼 수 있듯이, 맨 앞에 새로운 차원이 생겨 배열 내의 텐서 개수만큼의 크기가 된 것을 볼 수 있따.
# 즉, 새로운 차원을 만든 뒤, 이어 붙이기(cat 함수)를 수행한 것과 같다.

# 새롭게 생겨날 차원의 인덱스를 직접 지정할 수도 있다.
z = torch.stack([x, y], dim=-1)
print(z)
'''
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
'''
print(z.size()) # torch.Size([3, 3, 2])

# stack 함수는 새로운 차원을 만든 뒤, cat 함수를 수행한 것과 같다.
# unsqueeze 함수와 cat 함수를 사용해서 동일하게 구현할 수 있다.
d = 0
z = torch.cat([x.unsqueeze(d), y.unsqueeze(d)], dim=d)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [55]:
# cat 함수나 stack 함수는 실전에서 유용하게 사용될 때가 많다.
# 특히 여러 이터레이션(iteration)을 돌며 반복되는 작업을 수행한 후 반복 작업의 결과물을 하나로 합치는데 사용된다.
# 이 경우에는 주로 다음 코드와 같은 형태를 띄게 된다.
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2)
    result += [x]

result = torch.stack(result)
# result라는 빈 배열(리스트)을 만든 후, 결과물(텐서 x)을 result에 차례대로 추가(append)한 후, stack 또는 cat 함수를 통해 하나의 텐서로 만드는 작업이다.
print(result)
print(result.size())

tensor([[[0.0000e+00, 1.0526e-05],
         [4.1773e-03, 7.4409e-43]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[       nan, 2.6848e-06],
         [1.1210e-44, 0.0000e+00]],

        [[1.0842e-19, 5.2207e-01],
         [2.8026e-44, 0.0000e+00]]])
torch.Size([5, 2, 2])


In [59]:
# 다양한 기타 함수
# 1. expand 함수
# expand 함수는 차원의 크기가 1인 차원을 원하는 크기로 늘려주는 함수이다.
# 동일한 텐서를 그냥 반복하여, 리스트에 넣고, cat 함수를 해당 차원에 대하여 수행하는 것과 동일하다.
x = torch.FloatTensor([[[1, 2]], [[3, 4]]])
print(x.size()) # torch.Size([2, 1, 2])
# 위의 코드와 같이 두 번째 차원의 크기가 1인 텐서가 존재할 때 다음 코드처럼 expand를 수행할 수 있다.
# 여기선, 두 번째 차원의 크기를 3으로 늘린다.
y = x.expand(2, 3, 2)
print(y)
'''
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
'''
print(y.size()) # torch.Size([2, 3, 2])
# 이것을 cat 함수를 통해 구현하면 다음과 같다.
y = torch.cat([x] * 3, dim=1)
print(y)
'''
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
'''

torch.Size([2, 1, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])
tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [60]:
# 2. random permutation 함수
# randperm 함수는 랜덤 수열을 생성하는 파이토치 함수이다.
# 딥러닝은 랜덤성에 의존하는 부분이 많기 때문에 필요에 따라 이 함수를 활용할 수 있다.
# randperm 함수의 인자로 숫자를 넣어주면, 1부터 해당 숫자까지의 정수를 임의의 순서로 텐서에 넣어 반환한다.
x = torch.randperm(10)
print(x) # tensor([1, 6, 5, 3, 0, 2, 9, 4, 8, 7])
print(x.size()) # torch.Size([10])

tensor([1, 6, 5, 3, 0, 2, 9, 4, 8, 7])
torch.Size([10])


In [62]:
# 3. Argument Max 함수
# argmax 함수는 수식에서도 굉장히 많이 활용된다.
# argmax는 함수의 출력값을 최대로 만드는 입력값을 반환하는 함수이다.
x = torch.randperm(3 ** 3).reshape(3, 3, -1)
print(x)
'''
tensor([[[ 1, 26, 25],
         [18,  3,  4],
         [13, 10,  8]],

        [[20, 15, 24],
         [ 0,  9, 17],
         [ 5, 19,  7]],

        [[16,  2, 11],
         [21, 23, 12],
         [ 6, 14, 22]]])
'''
print(x.size()) # torch.Size([3, 3, 3])
# 다음과 같이 argmax 함수를 사용한다.
y = x.argmax(dim=-1)
print(y)
'''
tensor([[2, 0, 2],
        [0, 2, 2],
        [0, 0, 2]])
'''
print(y.size()) # torch.Size([3, 3])
# argmax 함수의 인수로 차원의 인덱스를 -1로 지정했기에, 다른 차원들이 같은 값 중에서 가장 큰 값의 인덱스를 반환한다.

tensor([[[ 0,  5,  9],
         [19,  1,  4],
         [23,  7, 26]],

        [[11, 10,  6],
         [22,  8, 24],
         [ 2, 12, 20]],

        [[25, 13, 17],
         [15,  3, 14],
         [18, 16, 21]]])
torch.Size([3, 3, 3])
tensor([[2, 0, 2],
        [0, 2, 2],
        [0, 0, 2]])
torch.Size([3, 3])


In [67]:
# 4. Top-k 함수
# argmax 함수의 상우 ㅣ호환 버전이다.
# topk 함수는 가장 큰 k 개의 값과 인덱스를 모두 반환한다.
# 앞서 선언한 텐서 x에 대하여, topk 함수를 수행한 결과이다.
values, indices = torch.topk(x, k=1, dim=-1)
print(values.size()) # torch.Size([3, 3, 1])
print(indices.size()) # torch.Size([3, 3, 1])

# topk 함수는 상위 k개 값과 인덱스를 모두 반환하기에, 반환값을 튜플로 받는 것을 볼 수 있다.
# 현재는 k = 1이므로, values와 indices의 마지막 차원의 크기가 1로 되어 있다.
# 만일 k를 1보다 더 큰 값을 쓸 경우, 반환되는 텐서의 크기는 다음과 같이 바뀐다.
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size()) # torch.Size([3, 3, 2])

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])
torch.Size([3, 3, 2])


In [69]:
# 5. sort 함수
# 앞서 선언한 텐서 x를 원하는 차원을 기준으로 정렬한 후, k개를 추출한다.
# 즉, 결과물은 topk 함수와 동일하다.
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size()) # torch.Size([3, 3, 2])

# topk를 통해 sort 함수를 구현할 수 있다.
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)

print(values)
'''
tensor([[[ 9,  5,  0],
         [19,  4,  1],
         [26, 23,  7]],

        [[11, 10,  6],
         [24, 22,  8],
         [20, 12,  2]],

        [[25, 17, 13],
         [15, 14,  3],
         [21, 18, 16]]])
'''
# 결과물을 보면, 마지막 차원 내에서만 내림차순으로 정렬된 것을 볼 수 있따.

torch.Size([3, 3, 2])
tensor([[[ 9,  5,  0],
         [19,  4,  1],
         [26, 23,  7]],

        [[11, 10,  6],
         [24, 22,  8],
         [20, 12,  2]],

        [[25, 17, 13],
         [15, 14,  3],
         [21, 18, 16]]])


In [73]:
# 6. Masked Fill 함수
# 텐서 내의 원하는 부분만 특정 값으로 바꿔치기한다.
# 아래는 3 x 3 크기의 텐서의 내부 값을 0부터 8까지 순서대로 갖도록 하는 코드이다.
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)
print(x)
'''
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
'''
print(x.size()) # torch.Size([3, 3])

# 논리 연산자를 통해, 불리언 텐서를 만든다.
mask = x > 4
print(mask)
'''
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
'''
# 이 mask를 통해서, masked_fill 함수를 수행한다면, 4보다 큰 값을 갖는 요소들을 특정 값으로 치환할 수 있따.
# 아래 코드는 4보다 큰 값들을 모두 -1로 한 번에 치환하도록 하는 코드이다.
y = x.masked_fill(mask, value=-1)
print(y)
'''
tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])
'''

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


In [75]:
# 7. Ones, Zeros 함수
# 아래는 1로 가득찬 2 x 3 텐서와, 0으로 가득 찬 같은 크기의 텐서를 구하는 코드이다.
print(torch.ones(2, 3))
'''
tensor([[1., 1., 1.],
        [1., 1., 1.]])
'''
print(torch.zeros(2, 3))
'''
tensor([[0., 0., 0.],
        [0., 0., 0.]])
'''
# 또는 ones_like와 zeros_like 함수를 통해, 특정 텐서와 같은 크기의 0 또는 1 텐서를 만들 수 있다.
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(x.size()) # torch.Size([2, 3])
print(torch.ones_like(x))
'''
tensor([[1., 1., 1.],
        [1., 1., 1.]])
'''
print(torch.zeros_like(x))
'''
tensor([[0., 0., 0.],
        [0., 0., 0.]])
'''

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
