In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print(type(array1))
print(array1.shape)

In [ ]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])
print(type(array2))
print(array2.shape)

In [ ]:
array3 = np.array([[1, 2, 3]])
print(type(array3))
print(array3.shape)

In [ ]:
# dim = 차원을 의미한다. ndim = n차원을 의미한다.
print(array1.ndim,array2.ndim,array3.ndim)

In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

In [ ]:
# 각 항목의 데이터 타입이 다른 경우
# 큰 데이터 타입으로 변환한다.
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

In [ ]:
# 각 항목의 데이터 타입을 형 변환
# astype()을 이용하여 데이터의 타입을 변환한다.

array_int = np.array([1, 2, 3])
array_float = array_int.astype("float64") 
print(array_float, array_float.dtype) # [1. 2. 3.] float64

array_int1 = array_float.astype('int32') 
print(array_int1, array_int1.dtype) # [1 2 3] int32

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype) # [1 2 3] int32

In [ ]:
# arange(숫자)
# - range와 비슷하게 0부터 숫자 -1까지
sequence_array= np.arange(10) # 0부터 9까지
print(sequence_array) # [0 1 2 3 4 5 6 7 8 9]
print(sequence_array.dtype, sequence_array.shape) # int32 (10,) (10, ) <- 튜플을 의미한다.

# arange(숫자1, 숫자2)
# - 숫자1부터 숫자2 - 1까지
sequence_array2 = np.arange(5, 10)
print(sequence_array2) # [5 6 7 8 9]
print(sequence_array2.dtype, sequence_array2.shape) # int32 (5,)

In [ ]:
# zeors
# - 모두 0으로 채운 ndarray 반환
# - dtype을 입력하지 않으면 기본은 float64
zero_array = np.zeros((3, 2), dtype='int32') # 모두 0으로 채워진, 3행 2열의 ndarray를 만든다.
print(zero_array)
'''
[[0 0]
 [0 0]
 [0 0]]
'''
print(zero_array.dtype, zero_array.shape) # int32 (3, 2)

In [ ]:
'''
ones
- 모두 1로 채운 ndarray를 반환한다.
- dtype을 입력하지 않으면 기본은 float64이다.
'''
one_array = np.ones((3,2))
print(one_array)
'''
[[1. 1.]
 [1. 1.]
 [1. 1.]]
'''
print(one_array.dtype, one_array.shape) # float64 (3, 2)

In [ ]:
'''
reshape
- 차원과 크기 변경
- 지정한 차원과 크기로 변경하지 못하면 오류가 발생한다.
'''

array1 = np.arange(10)
print(array1) # [0 1 2 3 4 5 6 7 8 9] (1차원)
array2 = array1.reshape(2, 5)
print(array2)
'''(2차원)
[[0 1 2 3 4]
 [5 6 7 8 9]]
'''
array3 = array1.reshape(5, 2)
print(array3)
'''
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
'''
# array3 = array1.reshape(4, 3) <- array1의 요소의 개수는 10개인데, 4 by 3 즉, 12개의 요소가 필요하기에 에러가 발생한다.


In [ ]:
'''
reshape
- 자동으로 처리하기 : -1
- reshape를 사용할 때 -1을 사용하면, 자동으로 정렬해준다.
'''
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5) # 행의 개수는 자동으로, 열의 개수는 5개로 즉, 행은 2가 된다.
print(array2.shape)
array3 = array1.reshape(5, -1) # 행의 개수는 5개로, 열의 개수는 자동으로 즉, 열은 2가된다.
print(array3.shape)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print(array3d, array3d.shape)
'''
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
'''
array5 = array3d.reshape(-1 ,1)
print(array5, array5.shape)
'''
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)
'''
array6 = array1.reshape(-1, 1)
print(array6, array6.shape)
'''
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)
'''

In [ ]:
'''
단일 값 추출
- []
'''
array1 = np.arange(1, 10)
print(array1) # [1 2 3 4 5 6 7 8 9]
value = array1[2]
print(value, type(value)) # 3 <class 'numpy.int32'>

# 인덱스가 음수이면, 뒤에서부터 계산한다.
print(array1[-1], array1[-2]) # 9 8

In [ ]:
'''
값 수정
'''
array1[0] = 9
array1[8] = 0
print(array1)

In [ ]:
# 다차원의 경우
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)
print(array2d[0, 0])
print(array2d[0, 1])
print(array2d[1, 0])
print(array2d[2, 2])


In [ ]:
'''
슬라이싱
- [시작인덱스 : 종료인덱스]:
- 시작인덱스부터 종료인덱스 -1까지
'''
array1 = np.arange(1, 10)
print(array1) # [1 2 3 4 5 6 7 8 9]
array3 = array1[0:3]
print(array3) # [1 2 3]
print(type(array3)) # <class 'numpy.ndarray'>
'''
슬라이싱
- 시작 / 종료 인덱스 생략
'''
array1 = np.arange(1, 10)
print(array1) # [1 2 3 4 5 6 7 8 9]
array4 = array1[:3]
print(array4) # [1 2 3]
array5 = array1[3:]
print(array5) # [4 5 6 7 8 9]
array6 = array1[:]
print(array6) # [1 2 3 4 5 6 7 8 9]
'''
슬라이싱
- 다차원의 경우
'''
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)
'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
'''
print(array2d[0 : 2, 0 : 2])
'''
[[1 2]
 [4 5]]
'''
print(array2d[1 : 3, 0 : 3])
'''
[[4 5 6]
 [7 8 9]]
'''
print(array2d[1 : 3,   :  ])
'''
[[4 5 6]
 [7 8 9]]
'''
print(array2d[  :  ,   :  ])
'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
'''
print(array2d[  : 2, 1 :  ])
'''
[[2 3]
 [5 6]]
'''
print(array2d[  : 2,   0  ]) # 마지막 0은 슬라이싱이 아님, 즉, 기존의 [[1, 2, 3], [4, 5, 6]]에서 첫 번째 열을 선택한다. 즉, [1, 4]가 반환된다.
''' 기존 2차원 배열에서 1차원 배열이 되었다. -> 차원이 줄어들었다.
[1 4]
'''

In [ ]:
'''
슬라이싱
- 다차원의 경우
'''
array1d = np.arange(1, 10)
aray2d = array1d.reshape(3, 3)
print(array2d)
'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
'''
print(array2d[0]) # [1 2 3] (2차원 -> 1차원 즉, 차원이 줄어든다.)
print(array2d[1]) # [4 5 6] (2차원 -> 1차원 즉, 차원이 줄어든다.)
print(array2d.shape) # (3, 3) (2차원 -> 1차원 즉, 차원이 줄어든다.)
print(array2d[0].shape) # (3,) (2차원 -> 1차원 즉, 차원이 줄어든다.)
print(array2d[0].shape) # (3,) (2차원 -> 1차원 즉, 차원이 줄어든다.)

In [ ]:
'''
팬시 인덱싱(Fancy Indexing)
- 리스트나 ndarray로 인덱스 집합을 지정하면, 해당 인덱스의 값들로 ndarray를 반환한다.
'''

array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)
'''
[[1 2 3]
 [4 5 6]
 [7 8 9]]
'''
array3 = array2d[[0, 1], 2] # 0번째 행과 1번째 행을 추출하고, 추출한 배열에서 2번째 열을 가져온다.
print(array3) # [3 6]
array4 = array2d[[0, 1], 0 : 2] # 0번째 행과 1번째 행을 추출하고, 추출한 배열에서 0부터 1까지 슬라이싱한다.
print(array4)
'''
[[1 2]
 [4 5]]
'''
array5 = array2d[[0, 1]] # 0번째 행과 1번째 행을 추출한다.
print(array5)
'''
[[1 2 3]
 [4 5 6]]
'''
array6 = array2d[[0, 2], 1] # 0번째 행과 2번째 행을 추출한 후, 추출한 배열에서 1번째 열을 가져온다.
print(array6) # [2 8]

In [ ]:
'''
불리언 인덱싱
- 조건문을 만족하는 항목만 추출한다.
'''
array1d = np.arange(1, 10)
array3 = array1d[array1d > 5]
print(array3) # [6 7 8 9]
print(array1d > 5) # [False False False False False  True  True  True  True]

In [ ]:
# 행렬 정렬
'''
numpy의 sort 함수는 복사하여 정렬하고 결과를 반환한다.
ndarray의 sort 함수는 원본을 정렬한다.
'''
# 오름차순 정렬
org_array = np.array([3, 1, 9, 5])
print(org_array) # [3 1 9 5]
sort_array1 = np.sort(org_array) # 넘파이가 가지고 있는 sort 함수
print(sort_array1) # [1 3 5 9]
print(org_array) # [3 1 9 5]
sort2_array = org_array.sort() # ndarray가 가지고 있는 sort 함수
print(sort2_array) # None -> 원본값 자체를 바꾸기에 return 값이 없다. 즉, 결과는 org_array에 저장된다.
print(org_array) # [1 3 5 9]

# 내림차순 정렬
# sort()를 이용하여 오름차순으로 정렬한 것을 뒤집어서 내림차순으로 만든다.
org_array = np.array([3, 1, 9, 5])
print(org_array) # [3 1 9 5]
sort_array1 = np.sort(org_array)[::-1] # [A : B : C] -> A부터 B까지 C 간격으로
print(sort_array1) # [9 5 3 1]
print(org_array) # [3 1 9 5]

In [ ]:
'''
행렬 정렬
다차원의 경우 axis를 설정하여 정렬한다.
axis = 0일 경우 아래 방향으로 정렬한다. ↓
axis = 1일 경우 오른쪽 방향으로 정렬한다. →
'''
array2d = np.array([[8, 12], [7, 1]])
print(array2d)
'''
[[ 8 12]
 [ 7  1]]
'''
array0 = np.sort(array2d, axis=0)
print(array0)
'''
[[ 7  1]
 [ 8 12]]
'''
array1 = np.sort(array2d, axis=1)
print(array1)
'''
[[ 8 12]
 [ 1  7]]
'''

In [ ]:
'''
정렬된 행렬의 인덱스 반환
np.argsort()를 이용하면, 값이 정렬된 후, 값이 정렬되기 전의 인덱스를 반환한다.
'''
org_array = np.array([3, 1, 9, 5])
print(org_array) # [3 1 9 5]
sort_indices = np.argsort(org_array)
print(sort_indices) # [1 0 3 2]

In [ ]:
'''내림차순'''
org_array = np.array([3, 1, 9, 5])
print(org_array) # [3 1 9 5]
sort_indices = np.argsort(org_array)[ : : -1]
print(sort_indices) # [2 3 0 1]

name_array = np.array(["John", "Mike", "Sarah", "Kate", "Samuel"])
score_array = np.array([78, 95, 84, 98, 88])
sort_indices = np.argsort(score_array)
print(sort_indices) # [0 2 4 1 3]
print(name_array[sort_indices]) # ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']

In [ ]:
'''
행렬 내적(행렬 곱)
np.dot()을 이용하여 행렬의 곱을 구현할 수 있다.
'''
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[ 7, 8], [9, 10], [11, 12]])
dot_product = np.dot(A, B)
print(A)
'''
[[1 2 3]
 [4 5 6]]
'''
print(B)
'''
[[ 7  8]
 [ 9 10]
 [11 12]]
'''
print(dot_product)
'''
[[ 58  64]
 [139 154]]
'''

In [ ]:
'''
전치 행렬
np.transpose()를 사용하여 전치 행렬을 만들 수 있다.
'''
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print(A)
'''
[[1 2]
 [3 4]]
'''
print(transpose_mat)
'''
[[1 3]
 [2 4]]
'''